name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: systemic-engineering/ci/actions/nix-setup@main

      - name: Test
        run: nix develop -c cargo test

      - name: Publish to crates.io
        run: nix develop -c cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
