name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: systemic-engineering/ci/actions/nix-setup@main

      - name: Download deps
        run: nix develop -c gleam deps download

      - name: Test
        run: nix develop -c gleam test

      - name: Format check
        run: nix develop -c gleam format --check src test
